language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="mirage-nat:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="mirage-nat" OCAML_VERSION="3.12.1"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.00.1"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.01.0"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.02.3"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.03.0"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.04.2"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.05.0"
  - PACKAGE="mirage-nat" OCAML_VERSION="4.06.0"
